// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PDI.NetCoreDemos.Data;
using System;

namespace PDI.NetCoreDemos.Migrations
{
    [DbContext(typeof(VCardContext))]
    partial class VCardContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PDI.NetCoreDemos.Models.VCardDto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Categories");

                    b.Property<string>("FirstName");

                    b.Property<string>("FormattedName");

                    b.Property<string>("JobTitle");

                    b.Property<string>("LastName");

                    b.Property<DateTime>("LastRevision");

                    b.Property<string>("MiddleName");

                    b.Property<string>("Nickname");

                    b.Property<string>("Organization");

                    b.Property<string>("Role");

                    b.Property<string>("SortString");

                    b.Property<string>("SortableName");

                    b.Property<string>("Suffix");

                    b.Property<string>("Title");

                    b.Property<string>("Units");

                    b.Property<string>("Version");

                    b.HasKey("ID");

                    b.ToTable("VCardDTO");
                });
#pragma warning restore 612, 618
        }
    }
}
